server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 169.254.109.128
    port: 6379

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.entity
  configuration:
    mapUnderscoreToCamelCase: false

logging:
  level:
    com:
      example:
        mapper : debug